### ISSUE TITLE
Can't read fit file

### ISSUE THREAD

**Issue by cassiel74** [cran/cycleRtools#1]
That's the error

```
Reading .fit file...
Exception in thread "main" com.garmin.fit.FitRuntimeException: FIT decode error: Protocol version 2.0 not supported.  Must be 1.15 or earlier.
	at com.garmin.fit.Decode.read(Decode.java:501)
	at com.garmin.fit.Decode.resume(Decode.java:295)
	at com.garmin.fit.Decode.read(Decode.java:272)
	at com.garmin.fit.csv.CSVTool.main(CSVTool.java:176)
Error in file(file, "rt") : non posso aprire questa connessione
Inoltre: Warning message:
In file(file, "rt") :
  cannot open file '/tmp/RtmpAysTTv/file53cb4a772cf3_data.csv': File o directory non esistente
```

**Comment by ratnanil** [comment]
I'm having the same issue.. have you found a solution for this?

**Comment by cassiel74** [comment]
nope..

**Comment by ratnanil** [comment]
This seems to be a read-only repo for CRAN. [The original repo](https://github.com/jmackie/fitdc) seems to be archived, what a bummer 👎 . I've switched to using the python package [`fitparse`](https://github.com/dtcooper/python-fitparse).
